# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/Mi8937/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/Mi8953

PRODUCT_COPY_FILES += \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/acdbdata/mido/QRD_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/mido/QRD_Bluetooth_cal.acdb \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/acdbdata/mido/QRD_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/mido/QRD_General_cal.acdb \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/acdbdata/mido/QRD_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/mido/QRD_Global_cal.acdb \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/acdbdata/mido/QRD_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/mido/QRD_Handset_cal.acdb \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/acdbdata/mido/QRD_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/mido/QRD_Hdmi_cal.acdb \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/acdbdata/mido/QRD_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/mido/QRD_Headset_cal.acdb \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/acdbdata/mido/QRD_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/mido/QRD_Speaker_cal.acdb \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/acdbdata/ysl/MTP_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ysl/MTP_Bluetooth_cal.acdb \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/acdbdata/ysl/MTP_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ysl/MTP_General_cal.acdb \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/acdbdata/ysl/MTP_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ysl/MTP_Global_cal.acdb \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/acdbdata/ysl/MTP_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ysl/MTP_Handset_cal.acdb \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/acdbdata/ysl/MTP_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ysl/MTP_Hdmi_cal.acdb \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/acdbdata/ysl/MTP_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ysl/MTP_Headset_cal.acdb \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/acdbdata/ysl/MTP_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ysl/MTP_Speaker_cal.acdb \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/acdbdata/ysl/MTP_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ysl/MTP_workspaceFile.qwsp \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/acdbdata/ysl/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ysl/adsp_avs_config.acdb \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/acdbdata/vince/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/vince/adsp_avs_config.acdb \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/acdbdata/vince/QRD_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/vince/QRD_Bluetooth_cal.acdb \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/acdbdata/vince/QRD_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/vince/QRD_General_cal.acdb \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/acdbdata/vince/QRD_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/vince/QRD_Global_cal.acdb \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/acdbdata/vince/QRD_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/vince/QRD_Handset_cal.acdb \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/acdbdata/vince/QRD_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/vince/QRD_Hdmi_cal.acdb \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/acdbdata/vince/QRD_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/vince/QRD_Headset_cal.acdb \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/acdbdata/vince/QRD_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/vince/QRD_Speaker_cal.acdb \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/acdbdata/vince/QRD_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/vince/QRD_workspaceFile.qwsp

PRODUCT_COPY_FILES += \
    vendor/xiaomi/Mi8953/proprietary/vendor/firmware/novatek_ts_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw.bin \
    vendor/xiaomi/Mi8953/proprietary/vendor/firmware/tas2557_uCDSP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tas2557_uCDSP.bin

PRODUCT_COPY_FILES += \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/overlayfs/vince/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_VENDOR)/etc/overlayfs/vince/sensors/sensor_def_qcomdev.conf \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/overlayfs/ysl/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_VENDOR)/etc/overlayfs/ysl/sensors/sensor_def_qcomdev.conf \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/overlayfs/mido/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_VENDOR)/etc/overlayfs/mido/sensors/sensor_def_qcomdev.conf

PRODUCT_COPY_FILES += \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/diracmobile.config:$(TARGET_COPY_OUT_VENDOR)/etc/diracmobile.config \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/perf/commonresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/commonresourceconfigs.xml \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/perf/commonsysnodesconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/commonsysnodesconfigs.xml \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/perf/perfboostsconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfboostsconfig.xml \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/perf/perfconfigstore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfconfigstore.xml \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/perf/targetconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetconfig.xml \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/perf/targetresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetresourceconfigs.xml \
    vendor/xiaomi/Mi8953/proprietary/vendor/firmware/a506_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a506_zap.b00 \
    vendor/xiaomi/Mi8953/proprietary/vendor/firmware/a506_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a506_zap.b01 \
    vendor/xiaomi/Mi8953/proprietary/vendor/firmware/a506_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a506_zap.b02 \
    vendor/xiaomi/Mi8953/proprietary/vendor/firmware/a506_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a506_zap.mdt \
    vendor/xiaomi/Mi8953/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    vendor/xiaomi/Mi8953/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw

PRODUCT_COPY_FILES += \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc \
    vendor/xiaomi/Mi8953/proprietary/vendor/etc/init/android.hardware.keymaster@3.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@3.0-service-qti.rc

PRODUCT_PACKAGES += \
    libsensor1 \
    libDiracAPI_SHARED \
    libdirac \
    gatekeeper.msm8953 \
    keystore.msm8953 \
    libsensor_reg \
    sensors.ssc \
    dirac_resource \
    libdirac-capiv2 \
    com.qualcomm.qti.uceservice@2.0 \
    uceShimService \
    com.qualcomm.qti.uceservice-V2.0-java \
    hvdcp_opti \
    sensors.qti \
    android.hardware.gatekeeper@1.0-service-qti \
    android.hardware.gatekeeper@1.0-impl-qti \
    android.hardware.keymaster@3.0-service-qti \
    android.hardware.keymaster@3.0-impl-qti \
    libkeymasterdeviceutils \
    libkeymasterprovision \
    libkeymasterutils
